name: testApi-k6
on: push
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test
      - run: go run main.go token.go user.go
      - name: Run k6 local test
        uses: k6io/action@v0.2.0
        with:
          filename: k6_test.js